name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: mgl-uhou # Substitua pelo seu nome de usuário
          svg_file_path: assets/github-contribution-grid-snake.svg

      - name: Commit and push
        run: |
          git config --global user.name "mgl-uhou" # Substitua pelo seu nome de usuário ou nome real
          git config --global user.email "miguelferreiralaurentino@gmail.com" # Substitua pelo seu e-mail
          git add assets/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push
